### ISSUE TITLE
Update to phf 8.0

### ISSUE THREAD

**Issue by tensor-programming** [tilpner/includedir#12]
Been getting these `attempt to calculate the remainder with a divisor of zero` errors from phf 0.7.24 in our project Tauri.  According to the phf github this is a known issue that was resolved in 0.8. You can find associated issues [here](https://github.com/sfackler/rust-phf/issues/111) 

Is there any way that you could update the library to 8.0 to help remove these problems?

**Comment by tilpner** [comment]
phf has been upgraded to 0.8.0 now, sorry it took so long.
